[package]
name = "domain"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
bson = "2.8"
thiserror = "1.0"
async-trait = "0.1"